name: collection_extension
description: A starting point for Dart libraries or applications.
version: 1.0.0
homepage: https://github.com/EmanuelLamba/collection_extension

environment:
  sdk: ">=2.17.6 <3.0.0"

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
